<h1>Dashboard</h1>

<div class="row">
    <div class="col-md-3">
        <div class="card bg-danger text-white">
            <strong>Minhas Apostas</strong>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-danger text-white">
            <strong>Minhas Apostas</strong>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-danger text-white">
            <strong>Minhas Apostas</strong>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card bg-danger text-white">
            <strong>Minhas Apostas</strong>
        </div>
    </div>
</div>