<div class="container mr-5">
    <div class="row">
        <div class="col">
            <img width="100%" src="https://blog.royalpag.com/wp-content/uploads/2017/12/129741-a-importancia-de-saber-quanto-apostar-e-quando-apostar.jpg">
        </div>
        <div class="col">
            <h3 class="text-center">Faça seu Login para apostar!!!</h3>


            <form method="post" action="">
                <label for="email">EMAIL:</label>
                <input name="email" type="email" id="email" class="form-control" placeholder="Digite seu E-mail">
                <br>
                <label for="password">SENHA:</label>
                <input name="password" type="password" id="password" class="form-control" placeholder="Digite sua Senha">
                <br>
                <button class="btn btn-danger btn-lg btn-block">Entrar</button>
                <br>
                <a href="/usuario/adicionar" class="text-center">Esqueci minha senha</a>
            </form>
        </div>
    </div>
</div>