<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Projeto de Apostas</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    </head>
    <body class="container">
    
        <div class="mt-5">
            <h1>Projeto de Apostas</h1>
            <hr>
        </div>
        <?php \App\Controller\AbstractController::navbar();?>

        <?php
            if (isset($_GET['error'])) {
                echo "
                    <div class='alert alert-danger'>
                        {$_GET['error']}
                    </div>
                ";
            }
        ?>

        <div class="card card-body mt-5">
            <?php main(); ?>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    </body>
</html>