<h1>Cadastro de Categorira</h1>

<form action="" method="post">
    <label for="name">Nome</label>
    <input type="text" name="name" id="name" placeholder="Nome da categoria" class="form-control" required>
    <br>
    <label for="image">Imagem</label>
    <input type="file" name="image" id="image" class="form-control" required>
    <br>
    <label for="description">Descrição</label>
    <textarea name="description" id="description" placeholder="Descrição" class="form-control" required></textarea>
    <br>
</form>
<hr>