<h1>Adicionar usuario</h1>

<form action="" method="post">
    <label for="name">Nome</label>
    <input type="text" name="name" id="name" placeholder="Nome da categoria" class="form-control" required>
    <br>
    <label for="email">E-mail</label>
    <input type="text" name="email" id="email" placeholder="E-mail" class="form-control" required>
    <br>
    <label for="password">Senha</label>
    <input type="password" name="password" id="password" placeholder="Digite sua Senha" class="form-control" required>
    <br>
    <label for="image">Foto</label>
    <input type="file" name="image" id="image" class="form-control" required>
    <br>
    <label for="cpf">CPF</label>
    <input type="number" name="cpf" id="cpf" placeholder="Digite seu CPF" class="form-control" required>
    <br>
</form>
<hr>

