<h1>Adicionar Aposta</h1>

<form action="" method="post">
    <label for="title">Título</label>
    <input type="text" name="title" id="title" placeholder="Nome da Aposta" class="form-control" required>
    <br>
    <label for="description">Descrição</label>
    <textarea name="description" id="description" placeholder="Descrição" class="form-control" required></textarea>
    <br>
    <label for="image">Imagem</label>
    <input type="file" name="image" id="image" class="form-control" required>
    <br>
    <label for="value">Valor</label>
    <input type="number" name="value" id="value" placeholder="Valor da Aposta" class="form-control" required>
    <br>
    <label for="commission">Comissão</label>
    <input type="number" name="commission" id="commission" placeholder="Comissão da casa" class="form-control" required>
    <br>
    <label for="date">Data</label>
    <input type="date" name="date" id="date" placeholder="Data do Resultado" class="form-control" required>
    <br>
</form>
<hr>