<form action="" method="post">
    <label for="make">Marca</label>
    <input type="text" name="make" id="make"  class="form-control">
    <br>

    <label for="model">Modelo</label>
    <input type="text" name="model" id="model"  class="form-control">
    <br>

    <label for="year">Ano</label>
    <input type="text" name="year" id="year"  class="form-control">
    <br>

    <label for="mileage">KM</label>
    <input type="text" name="mileage" id="mileage"  class="form-control">
    <br>

    <label for="plate">Placa</label>
    <input type="text" name="plate" id="plate"  class="form-control">
    <br>

    <button type="button" onclick="validarForm()" class="btn btn-primary btn-lg">Enviar</button>
</form>

<script src="/assets/js/vehicle/validateForm.js"></script>