<table class="table table-striped table-hover">
    <thead>
        <tr class="table-dark">
            <th>Marca</th>
            <th>Modelo</th>
            <th>Ano</th>
            <th>Km</th>
            <th>Placa</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($vehicles as $vehicle) {
                echo "
                    <tr>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Ano</th>
                        <th>Km</th>
                        <th>Placa</th>
                        <th>...</th>
                    </tr>
                ";
            }
        ?>
    </tbody>
</table>