<div class="ml-5">
    <div class="btn-group">
        <a class="btn btn-danger" href="/dashboard" >
            Dashboard
        </a>
    </div>
    <div class="btn-group">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categorias
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/categorias/listar">Listar</a>
            <a class="dropdown-item" href="/categorias/adicionar">Adicionar</a>
        </div>
    </div>
    <div class="btn-group">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Apostas
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/aposta/listar">Listar</a>
            <a class="dropdown-item" href="/aposta/adicionar">Adicionar</a>
        </div>
    </div>
    <div class="btn-group">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Usuários
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/usuario/listar">Listar</a>
            <a class="dropdown-item" href="/usuario/adicionar">Adicionar</a>
        </div>
    </div>
    <div class="btn-group">
        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Lance
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/lance/listar">Listar</a>
            <a class="dropdown-item" href="/lance/adicionar">Adicionar</a>
        </div>
    </div>
    <div class="btn-group form-inline my-2 my-lg-0">
        <div class="text-white mr-5">
            <a href="/sair" class="btn btn-danger">Sair</a>
        </div>
    </div>
</div>